env:
  matrix:
      - WITH_CMAKE=true VTK60=true ITK45=true PREBUILD_ITKVTK=true BUILD_SOLVER=false
      - WITH_CMAKE=true VTK60=true ITK45=true PREBUILD_ITKVTK=true BUILD_SOLVER=true

sudo: false
language: cpp

addons:
  apt:
    packages:
    - curl
    - cmake
    - tcl8.5
    - tk8.5
    - tcl8.5-dev
    - tk8.5-dev
    - tcllib
    - tklib
    - gfortran
    sources:
    - kubuntu-backports

compiler: gcc

git:
  submodules: false

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - export SCRIPTS=$cwd/travis
  - export EXTERNALS_DIR=/home/travis/external
  - export VTK_SOURCE_DIR=$EXTERNALS_DIR/vtk-6.0
  - export VTK_DIR=$EXTERNALS_DIR/vtk-6.0-build
  - export ITK_SOURCE_DIR=$EXTERNALS_DIR/itk-4.5
  - export ITK_DIR=$EXTERNALS_DIR/itk-4.5-build
  - export BUILD_DIR=$cwd/build
  # - sudo apt-get install -qq mpich2 tklib

cache:
  directories:
  - /home/travis/external/vtk-6.0
  - /home/travis/external/vtk-6.0-build
  - /home/travis/external/itk-4.5
  - /home/travis/external/itk-4.5-build

before_script:
  - $SCRIPTS/travis_build_vtk.sh
  - $SCRIPTS/travis_build_itk.sh
  - $SCRIPTS/travis_before_script_cleanup.sh
  #- if ! $WITH_CMAKE; then $ fi

script: $SCRIPTS/travis_build_and_test.sh

