language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: xenial
      sudo: required
      env: WITH_CMAKE=true SV_EXTERNALS_VERSION_NUMBER=2019.06 SV_EXTERNALS_USE_PREBUILT_QT=false
    - os: linux
      compiler: gcc
      dist: xenial
      sudo: required
      env: WITH_CMAKE=false SV_EXTERNALS_VERSION_NUMBER=2019.06 SV_EXTERNALS_USE_PREBUILT_QT=false
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      sudo: required
      env: WITH_CMAKE=true  SV_EXTERNALS_VERSION_NUMBER=2019.06 SV_EXTERNALS_USE_PREBUILT_QT=false
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      sudo: required
      env: WITH_CMAKE=false SV_EXTERNALS_VERSION_NUMBER=2019.06 SV_EXTERNALS_USE_PREBUILT_QT=false
    - os: windows
      env: WITH_CMAKE=true SV_EXTERNALS_VERSION_NUMBER=2019.06 SV_EXTERNALS_USE_PREBUILT_QT=false

addons:
  apt:
    packages:
    - libglu1-mesa-dev
    - libxt-dev
    - libxi-dev
    - libglew-dev
    - libxmu-dev

git:
  submodules: false

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cwd=$(pwd -W); fi
  - echo "CWD=$cwd"
  - export BUILD_DIR=$cwd/build
  - export SV_EXTERNALS_BIN_DIR=$cwd/sv_externals/bin
  - export SV_CODE_DIR=$cwd/Code
  - export SV_EXTERNALS_DIR=$cwd/Externals
  - export SV_EXTERNALS_BUILD_DIR=$SV_EXTERNALS_DIR/build
  - export SV_EXTERNALS_BIN_DIR=$SV_EXTERNALS_BUILD_DIR/sv_externals/bin
  - export SCRIPTS=$cwd/travis
  - if $SV_EXTERNALS_USE_PREBUILT_QT; then source $SCRIPTS/travis_get_system_qt.sh; fi
  - if $WITH_CMAKE; then $SCRIPTS/travis_get_cmake_latest.sh; fi

script: $SCRIPTS/travis_build.sh
